"""Populate this literal list before running the Phase 2 E2E diagnostic."""

QUERIES: list[str] = [
    "Need an answer I can send to an admin: We're on Growth in European Union. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    "Our Business workspace uses several API keys and together we're over 1,200 requests per minute. Can each key claim its own full limit, or is the limit shared?",
    "Customer is pushing back here: We're on Starter in United States. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    "This is from a real ticket-style scenario: Our Starter workspace uses several API keys and together we're over 300 requests per minute. Can each key claim its own full limit, or is the limit shared?",
    'I might be mixing two rules up. We upgraded from Business to Enterprise halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    'Customer is pushing back here: A Email assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'Need an answer I can send to an admin: A Business customer says a citation in an AI answer should count as a contract amendment. Is that what the policy says?',
    'Quick sanity check — We regenerated MFA recovery codes for an admin in a Starter workspace. Are unused codes from the old set still valid?',
    'Finance and support are telling me different things. We regenerated MFA recovery codes for an admin in a Enterprise workspace. Are unused codes from the old set still valid?',
    'Production support question: A Growth customer says a citation in an AI answer should count as a contract amendment. Is that what the policy says?',
    'I might be mixing two rules up. The right knowledge article exists, but an active metadata filter excludes its product line. Can the answer stage silently pull that article back in?',
    'The current help article and a signed Enterprise order form disagree about an API limit for this Enterprise account. Which source controls the negotiated limit?',
    'This is from a real ticket-style scenario: Our workspace is in Asia Pacific. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'Finance and support are telling me different things. A Enterprise production service is broadly unavailable with no reasonable workaround, but only one ticket is open. Is it still P1?',
    'Need an answer I can send to an admin: A Growth workspace has a legal hold on one record, but the normal retention period already expired. Should Atlas hard-delete it anyway?',
    'Need an answer I can send to an admin: The knowledge base is silent about a refund exception for this Starter case. Should the assistant infer an exception because it sounds fair?',
    'This is from a real ticket-style scenario: We upgraded from Business to Enterprise halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    'Customer is pushing back here: The current help article and a signed Enterprise order form disagree about an API limit for this Starter account. Which source controls the negotiated limit?',
    'Customer is pushing back here: A Growth team deleted a WhatsApp conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    'A Data Processing Addendum conflicts with general documentation on how customer data is processed in Canada. Which one controls that privacy question?',
    "We're on Business in European Union. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Need an answer I can send to an admin: We revoked a third-party connector token used by a Email integration. Does revocation automatically erase data imported last month?',
    'Finance and support are telling me different things. If our workspace content region is Canada, does that also force every billing record and anti-fraud signal to stay there?',
    "This is from a real ticket-style scenario: We're debugging a WhatsApp issue for a Starter workspace in United States. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Finance and support are telling me different things. A Security Addendum conflicts with a generic help-center article about a security commitment for a Business customer. Which should support follow?',
    "This is from a real ticket-style scenario: We're debugging a Email issue for a Enterprise workspace in United States. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    "Production support question: We're debugging a Zalo issue for a Starter workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Need an answer I can send to an admin: A Growth customer says a citation in an AI answer should count as a contract amendment. Is that what the policy says?',
    'Production support question: A Data Processing Addendum conflicts with general documentation on how customer data is processed in Asia Pacific. Which one controls that privacy question?',
    "Quick sanity check — We're debugging a Zalo issue for a Starter workspace in United States. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    "Production support question: Our WhatsApp webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    'Finance and support are telling me different things. A Security Addendum conflicts with a generic help-center article about a security commitment for a Growth customer. Which should support follow?',
    "Production support question: We're debugging a Zalo issue for a Business workspace in Canada. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'I might be mixing two rules up. We changed a knowledge source seconds ago for our Voice workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    'Customer is pushing back here: A Data Processing Addendum conflicts with general documentation on how customer data is processed in Asia Pacific. Which one controls that privacy question?',
    'Quick sanity check — We upgraded from Enterprise to Starter halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    'A Growth workspace has a legal hold on one record, but the normal retention period already expired. Should Atlas hard-delete it anyway?',
    'Need an answer I can send to an admin: We regenerated MFA recovery codes for an admin in a Growth workspace. Are unused codes from the old set still valid?',
    'I might be mixing two rules up. A Data Processing Addendum conflicts with general documentation on how customer data is processed in Asia Pacific. Which one controls that privacy question?',
    'A Zalo assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'Production support question: We upgraded from Business to Enterprise halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    'Customer is pushing back here: If our workspace content region is United States, does that also force every billing record and anti-fraud signal to stay there?',
    'Production support question: The knowledge base is silent about a refund exception for this Growth case. Should the assistant infer an exception because it sounds fair?',
    'Customer is pushing back here: Webhook verification works with the exact request bytes but fails after our framework parses and re-serializes JSON. Is that consistent with Atlas signing?',
    'Customer is pushing back here: We upgraded from Growth to Business halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    "I might be mixing two rules up. Our Starter workspace uses several API keys and together we're over 300 requests per minute. Can each key claim its own full limit, or is the limit shared?",
    'Customer is pushing back here: A Data Processing Addendum conflicts with general documentation on how customer data is processed in United States. Which one controls that privacy question?',
    'Finance and support are telling me different things. We revoked a third-party connector token used by a Web Chat integration. Does revocation automatically erase data imported last month?',
    'I might be mixing two rules up. A Starter team deleted a WhatsApp conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    'The knowledge base is silent about a refund exception for this Starter case. Should the assistant infer an exception because it sounds fair?',
    'This is from a real ticket-style scenario: A Enterprise production service is broadly unavailable with no reasonable workaround, but only one ticket is open. Is it still P1?',
    'What exact stock price will Atlas have next Friday?',
    "This is from a real ticket-style scenario: We're debugging a Web Chat issue for a Enterprise workspace in Canada. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    "Production support question: We're debugging a WhatsApp issue for a Enterprise workspace in Canada. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Need an answer I can send to an admin: A Security Addendum conflicts with a generic help-center article about a security commitment for a Enterprise customer. Which should support follow?',
    'We upgraded from Growth to Business halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    'Quick sanity check — Our workspace is in United States. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'Quick sanity check — A Growth production service is broadly unavailable with no reasonable workaround, but only one ticket is open. Is it still P1?',
    "I might be mixing two rules up. Our Business workspace uses several API keys and together we're over 1,200 requests per minute. Can each key claim its own full limit, or is the limit shared?",
    "Finance and support are telling me different things. We're debugging a Zalo issue for a Starter workspace in United States. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Production support question: Our workspace is in United States. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'I might be mixing two rules up. SCIM deactivated an agent in Canada. Should the audit events that person created disappear too?',
    'Production support question: A Growth team deleted a Voice conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    'I might be mixing two rules up. We think an API secret for a Growth workspace leaked. What immediate action does the documentation call for?',
    'Customer is pushing back here: We regenerated MFA recovery codes for an admin in a Business workspace. Are unused codes from the old set still valid?',
    'Quick sanity check — We think an API secret for a Starter workspace leaked. What immediate action does the documentation call for?',
    'I might be mixing two rules up. A Business customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    'Production support question: A major Zalo feature is unavailable for many users but we have a material workaround. Is that P1 or P2?',
    "Quick sanity check — We're debugging a WhatsApp issue for a Business workspace in Canada. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'A Business team deleted a WhatsApp conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    'Finance and support are telling me different things. The right knowledge article exists, but an active metadata filter excludes its product line. Can the answer stage silently pull that article back in?',
    "Quick sanity check — We're debugging a Zalo issue for a Enterprise workspace in Asia Pacific. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Quick sanity check — We revoked a third-party connector token used by a Zalo integration. Does revocation automatically erase data imported last month?',
    'I might be mixing two rules up. Our workspace is in United States. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'A Enterprise account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    'Finance and support are telling me different things. A Enterprise team deleted a Web Chat conversation 5 days ago, no legal hold. Is it still in the normal recovery window?',
    'I might be mixing two rules up. A Business team deleted a WhatsApp conversation 5 days ago, no legal hold. Is it still in the normal recovery window?',
    'This is from a real ticket-style scenario: A Business customer says a citation in an AI answer should count as a contract amendment. Is that what the policy says?',
    'Need an answer I can send to an admin: A Starter team deleted a Web Chat conversation 2 days ago, no legal hold. Is it still in the normal recovery window?',
    "We're debugging a Email issue for a Enterprise workspace in Asia Pacific. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Finance and support are telling me different things. A Growth customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    "Need an answer I can send to an admin: We're debugging a WhatsApp issue for a Growth workspace in Asia Pacific. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    "Need an answer I can send to an admin: We're debugging a Voice issue for a Enterprise workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Customer asked me this and I cannot find it in docs: Which competitor internal source code does Atlas reuse?',
    "This is from a real ticket-style scenario: Our Growth workspace uses several API keys and together we're over 600 requests per minute. Can each key claim its own full limit, or is the limit shared?",
    'Customer is pushing back here: A Starter account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    'Quick sanity check — A Growth customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    'I might be mixing two rules up. If our workspace content region is Canada, does that also force every billing record and anti-fraud signal to stay there?',
    'Production support question: Webhook verification works with the exact request bytes but fails after our framework parses and re-serializes JSON. Is that consistent with Atlas signing?',
    'Quick sanity check — We changed retention after a conversation was already hard-deleted. Can the new setting restore it?',
    'Finance and support are telling me different things. We sent the same supported create request twice on Starter with the same Idempotency-Key within an hour. Should that create two resources?',
    'This is from a real ticket-style scenario: A Starter workspace has a legal hold on one record, but the normal retention period already expired. Should Atlas hard-delete it anyway?',
    'Need an answer I can send to an admin: A Enterprise workspace has a legal hold on one record, but the normal retention period already expired. Should Atlas hard-delete it anyway?',
    'This is from a real ticket-style scenario: A Starter account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    'Customer is pushing back here: A Growth team deleted a Email conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    'Quick sanity check — We sent the same supported create request twice on Business with the same Idempotency-Key within an hour. Should that create two resources?',
    'Finance and support are telling me different things. The knowledge base is silent about a refund exception for this Enterprise case. Should the assistant infer an exception because it sounds fair?',
    'Finance and support are telling me different things. Our workspace is in United States. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'I might be mixing two rules up. Our workspace is in Canada. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    "Quick sanity check — Our Email webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    'Quick sanity check — A WhatsApp assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    "We're debugging a Voice issue for a Business workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Customer is pushing back here: We changed a knowledge source seconds ago for our Zalo workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    "I might be mixing two rules up. We're on Enterprise in Canada. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'This is from a real ticket-style scenario: The current help article and a signed Enterprise order form disagree about an API limit for this Starter account. Which source controls the negotiated limit?',
    'I might be mixing two rules up. A Growth customer says a citation in an AI answer should count as a contract amendment. Is that what the policy says?',
    'Customer is pushing back here: A Voice assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'Customer is pushing back here: We sent the same supported create request twice on Enterprise with the same Idempotency-Key within an hour. Should that create two resources?',
    'This is from a real ticket-style scenario: We changed a knowledge source seconds ago for our Email workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    'Production support question: The knowledge base is silent about a refund exception for this Business case. Should the assistant infer an exception because it sounds fair?',
    "I might be mixing two rules up. Our WhatsApp webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    "Finance and support are telling me different things. We're debugging a Voice issue for a Starter workspace in Asia Pacific. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    "We're debugging a Web Chat issue for a Enterprise workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Need an answer I can send to an admin: The current help article and a signed Enterprise order form disagree about an API limit for this Business account. Which source controls the negotiated limit?',
    "Finance and support are telling me different things. Our Voice webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    'Need an answer I can send to an admin: A Growth team deleted a WhatsApp conversation 5 days ago, no legal hold. Is it still in the normal recovery window?',
    'Finance and support are telling me different things. A Zalo assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    "Production support question: We're on Enterprise in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Need an answer I can send to an admin: A Business account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    'Need an answer I can send to an admin: A Enterprise customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    'Customer is pushing back here: Our workspace is in European Union. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'Quick sanity check — Our workspace is in European Union. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    "Production support question: We're debugging a Web Chat issue for a Enterprise workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'I might be mixing two rules up. We replayed a webhook; delivery ID changed but event ID stayed the same. Should our dedupe key be the event ID or the delivery ID?',
    "This is from a real ticket-style scenario: We're on Growth in United States. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Need an answer I can send to an admin: The current help article and a signed Enterprise order form disagree about an API limit for this Enterprise account. Which source controls the negotiated limit?',
    'Customer is pushing back here: A Business team deleted a Voice conversation 2 days ago, no legal hold. Is it still in the normal recovery window?',
    'I might be mixing two rules up. A Enterprise team deleted a Email conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    "Our Email webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    'Need an answer I can send to an admin: Our workspace is in European Union. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'Customer is pushing back here: We changed a knowledge source seconds ago for our Voice workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    'Need an answer I can send to an admin: A WhatsApp assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    "We're debugging a Voice issue for a Enterprise workspace in United States. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'This is from a real ticket-style scenario: A Starter customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    "Customer is pushing back here: We're debugging a Web Chat issue for a Business workspace in United States. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    "Customer is pushing back here: We're on Growth in Canada. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Need an answer I can send to an admin: A Starter team deleted a Voice conversation 2 days ago, no legal hold. Is it still in the normal recovery window?',
    "Need an answer I can send to an admin: We're on Growth in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'This is from a real ticket-style scenario: A Data Processing Addendum conflicts with general documentation on how customer data is processed in United States. Which one controls that privacy question?',
    'Production support question: A Business team deleted a WhatsApp conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    'We sent the same supported create request twice on Enterprise with the same Idempotency-Key within an hour. Should that create two resources?',
    'Customer is pushing back here: The right knowledge article exists, but an active metadata filter excludes its product line. Can the answer stage silently pull that article back in?',
    'We changed a knowledge source seconds ago for our Email workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    "I might be mixing two rules up. We're debugging a Zalo issue for a Business workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Production support question: A Enterprise team deleted a Email conversation 2 days ago, no legal hold. Is it still in the normal recovery window?',
    'Quick sanity check — We changed a knowledge source seconds ago for our Voice workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    'If our workspace content region is European Union, does that also force every billing record and anti-fraud signal to stay there?',
    'Finance and support are telling me different things. A Growth account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    'Need an answer I can send to an admin: A Data Processing Addendum conflicts with general documentation on how customer data is processed in Asia Pacific. Which one controls that privacy question?',
    'Production support question: We sent the same supported create request twice on Business with the same Idempotency-Key within an hour. Should that create two resources?',
    "Quick sanity check — We're on Business in Canada. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'The knowledge base is silent about a refund exception for this Enterprise case. Should the assistant infer an exception because it sounds fair?',
    "I might be mixing two rules up. We're on Starter in Canada. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Need an answer I can send to an admin: A Enterprise account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    'I might be mixing two rules up. We think an API secret for a Starter workspace leaked. What immediate action does the documentation call for?',
    "Need an answer I can send to an admin: Our Starter workspace uses several API keys and together we're over 300 requests per minute. Can each key claim its own full limit, or is the limit shared?",
    'Customer is pushing back here: A Data Processing Addendum conflicts with general documentation on how customer data is processed in European Union. Which one controls that privacy question?',
    'Need an answer I can send to an admin: A major Zalo feature is unavailable for many users but we have a material workaround. Is that P1 or P2?',
    'I might be mixing two rules up. We changed a knowledge source seconds ago for our Email workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    'This is from a real ticket-style scenario: We changed retention after a conversation was already hard-deleted. Can the new setting restore it?',
    'A Growth account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    "Production support question: We're on Growth in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'What is the guaranteed latency for every single request even during third-party outages?',
    'Need an answer I can send to an admin: If our workspace content region is European Union, does that also force every billing record and anti-fraud signal to stay there?',
    'Need an answer I can send to an admin: Our workspace is in United States. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'This is from a real ticket-style scenario: The knowledge base is silent about a refund exception for this Business case. Should the assistant infer an exception because it sounds fair?',
    'Quick sanity check — We upgraded from Growth to Business halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    'We revoked a third-party connector token used by a Web Chat integration. Does revocation automatically erase data imported last month?',
    'Finance and support are telling me different things. A Business production service is broadly unavailable with no reasonable workaround, but only one ticket is open. Is it still P1?',
    'I might be mixing two rules up. We sent the same supported create request twice on Starter with the same Idempotency-Key within an hour. Should that create two resources?',
    'I might be mixing two rules up. A Enterprise customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    'I might be mixing two rules up. A Business account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    'Production support question: Our workspace is in European Union. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'Production support question: A Business team deleted a Zalo conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    'Need an answer I can send to an admin: The current help article and a signed Enterprise order form disagree about an API limit for this Starter account. Which source controls the negotiated limit?',
    "Customer is pushing back here: We're on Starter in European Union. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Customer is pushing back here: A Zalo assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'Quick sanity check — We sent the same supported create request twice on Growth with the same Idempotency-Key within an hour. Should that create two resources?',
    "Need an answer I can send to an admin: We're debugging a Email issue for a Business workspace in Canada. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    "This is from a real ticket-style scenario: We're debugging a Voice issue for a Business workspace in Canada. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Need an answer I can send to an admin: A Enterprise team deleted a Zalo conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    "Customer is pushing back here: We're on Business in European Union. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Finance and support are telling me different things. A Starter team deleted a Voice conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    'This is from a real ticket-style scenario: A Enterprise team deleted a Zalo conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    'This is from a real ticket-style scenario: A Business team deleted a Voice conversation 5 days ago, no legal hold. Is it still in the normal recovery window?',
    'I might be mixing two rules up. We changed a knowledge source seconds ago for our Zalo workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    'Need an answer I can send to an admin: If our workspace content region is United States, does that also force every billing record and anti-fraud signal to stay there?',
    'We sent the same supported create request twice on Starter with the same Idempotency-Key within an hour. Should that create two resources?',
    'Finance and support are telling me different things. SCIM deactivated an agent in Canada. Should the audit events that person created disappear too?',
    "Finance and support are telling me different things. We're on Growth in United States. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Need an answer I can send to an admin: A Business team deleted a Voice conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    'Quick sanity check — A Starter team deleted a Email conversation 5 days ago, no legal hold. Is it still in the normal recovery window?',
    'Quick sanity check — We regenerated MFA recovery codes for an admin in a Growth workspace. Are unused codes from the old set still valid?',
    'Finance and support are telling me different things. A major Voice feature is unavailable for many users but we have a material workaround. Is that P1 or P2?',
    'Production support question: SCIM deactivated an agent in Asia Pacific. Should the audit events that person created disappear too?',
    'A major Web Chat feature is unavailable for many users but we have a material workaround. Is that P1 or P2?',
    'Quick sanity check — A Business team deleted a WhatsApp conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    'Customer is pushing back here: Our workspace is in United States. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'Customer is pushing back here: A Enterprise account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    'Finance and support are telling me different things. A Starter team deleted a WhatsApp conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    "Customer is pushing back here: We're debugging a Web Chat issue for a Growth workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Quick sanity check — We think an API secret for a Business workspace leaked. What immediate action does the documentation call for?',
    "This is from a real ticket-style scenario: We're debugging a Zalo issue for a Starter workspace in Canada. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'I might be mixing two rules up. SCIM deactivated an agent in United States. Should the audit events that person created disappear too?',
    'I might be mixing two rules up. A Email assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'Can a citation override a signed contract if the answer sounds more recent?',
    'Need an answer I can send to an admin: We revoked a third-party connector token used by a WhatsApp integration. Does revocation automatically erase data imported last month?',
    "Need an answer I can send to an admin: We're on Enterprise in Canada. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Quick sanity check — A Enterprise team deleted a Voice conversation 2 days ago, no legal hold. Is it still in the normal recovery window?',
    'Customer is pushing back here: A Growth production service is broadly unavailable with no reasonable workaround, but only one ticket is open. Is it still P1?',
    'Finance and support are telling me different things. A Business customer says a citation in an AI answer should count as a contract amendment. Is that what the policy says?',
    'A Business customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    'Customer is pushing back here: A major Web Chat feature is unavailable for many users but we have a material workaround. Is that P1 or P2?',
    "Need an answer I can send to an admin: Our Enterprise workspace uses several API keys and together we're over 3,000 requests per minute by default, with contracted overrides possible. Can each key claim its own full limit, or is the limit shared?",
    'We changed retention after a conversation was already hard-deleted. Can the new setting restore it?',
    'Production support question: A Growth production service is broadly unavailable with no reasonable workaround, but only one ticket is open. Is it still P1?',
    'Production support question: A WhatsApp assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'Need an answer I can send to an admin: We regenerated MFA recovery codes for an admin in a Starter workspace. Are unused codes from the old set still valid?',
    'This is from a real ticket-style scenario: A Enterprise customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    'Finance and support are telling me different things. We changed retention after a conversation was already hard-deleted. Can the new setting restore it?',
    'Quick sanity check — SCIM deactivated an agent in Asia Pacific. Should the audit events that person created disappear too?',
    "Production support question: We're debugging a WhatsApp issue for a Starter workspace in Asia Pacific. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Need an answer I can send to an admin: A Data Processing Addendum conflicts with general documentation on how customer data is processed in United States. Which one controls that privacy question?',
    'Production support question: The right knowledge article exists, but an active metadata filter excludes its product line. Can the answer stage silently pull that article back in?',
    'Customer is pushing back here: A Enterprise workspace has a legal hold on one record, but the normal retention period already expired. Should Atlas hard-delete it anyway?',
    'Quick sanity check — The current help article and a signed Enterprise order form disagree about an API limit for this Business account. Which source controls the negotiated limit?',
    'We upgraded from Business to Enterprise halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    'This is from a real ticket-style scenario: A Email assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'This is from a real ticket-style scenario: We regenerated MFA recovery codes for an admin in a Growth workspace. Are unused codes from the old set still valid?',
    'Need an answer I can send to an admin: A Enterprise customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    'This is from a real ticket-style scenario: A Starter team deleted a WhatsApp conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    'I might be mixing two rules up. A Starter account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    'Customer is pushing back here: A Business team deleted a Web Chat conversation 2 days ago, no legal hold. Is it still in the normal recovery window?',
    'The current help article and a signed Enterprise order form disagree about an API limit for this Starter account. Which source controls the negotiated limit?',
    "Customer is pushing back here: Our Starter workspace uses several API keys and together we're over 300 requests per minute. Can each key claim its own full limit, or is the limit shared?",
    'I might be mixing two rules up. A Enterprise production service is broadly unavailable with no reasonable workaround, but only one ticket is open. Is it still P1?',
    'I might be mixing two rules up. A Security Addendum conflicts with a generic help-center article about a security commitment for a Starter customer. Which should support follow?',
    'I might be mixing two rules up. A Starter customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    "Production support question: We're debugging a WhatsApp issue for a Growth workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'I might be mixing two rules up. A Enterprise customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    'Customer is pushing back here: A Business account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    "Finance and support are telling me different things. Our Enterprise workspace uses several API keys and together we're over 3,000 requests per minute by default, with contracted overrides possible. Can each key claim its own full limit, or is the limit shared?",
    "Need an answer I can send to an admin: We're on Business in United States. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Finance and support are telling me different things. A Business team deleted a Email conversation 2 days ago, no legal hold. Is it still in the normal recovery window?',
    'I might be mixing two rules up. A Security Addendum conflicts with a generic help-center article about a security commitment for a Growth customer. Which should support follow?',
    'I might be mixing two rules up. A Zalo assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'Finance and support are telling me different things. We replayed a webhook; delivery ID changed but event ID stayed the same. Should our dedupe key be the event ID or the delivery ID?',
    'Customer is pushing back here: The current help article and a signed Enterprise order form disagree about an API limit for this Business account. Which source controls the negotiated limit?',
    'This is from a real ticket-style scenario: SCIM deactivated an agent in Canada. Should the audit events that person created disappear too?',
    'Production support question: A Starter team deleted a WhatsApp conversation 5 days ago, no legal hold. Is it still in the normal recovery window?',
    'Production support question: A Security Addendum conflicts with a generic help-center article about a security commitment for a Enterprise customer. Which should support follow?',
    'This is from a real ticket-style scenario: We regenerated MFA recovery codes for an admin in a Starter workspace. Are unused codes from the old set still valid?',
    'A Web Chat assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'Finance and support are telling me different things. A Business customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    'I might be mixing two rules up. Can JIT create a new member on first SSO login just because the email domain matches, even if workspace policy disables JIT?',
    "I might be mixing two rules up. We're on Business in United States. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Need an answer I can send to an admin: We revoked a third-party connector token used by a Web Chat integration. Does revocation automatically erase data imported last month?',
    'Quick sanity check — Our workspace is in Asia Pacific. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'Production support question: A Enterprise team deleted a Voice conversation 2 days ago, no legal hold. Is it still in the normal recovery window?',
    'Finance and support are telling me different things. If our workspace content region is United States, does that also force every billing record and anti-fraud signal to stay there?',
    'Need an answer I can send to an admin: A Security Addendum conflicts with a generic help-center article about a security commitment for a Starter customer. Which should support follow?',
    'Finance and support are telling me different things. If our workspace content region is Asia Pacific, does that also force every billing record and anti-fraud signal to stay there?',
    'Quick sanity check — The right knowledge article exists, but an active metadata filter excludes its product line. Can the answer stage silently pull that article back in?',
    'Need an answer I can send to an admin: We upgraded from Growth to Business halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    'Customer is pushing back here: We think an API secret for a Business workspace leaked. What immediate action does the documentation call for?',
    'Customer is pushing back here: SCIM deactivated an agent in European Union. Should the audit events that person created disappear too?',
    'We changed a knowledge source seconds ago for our Voice workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    'Customer is pushing back here: We upgraded from Enterprise to Starter halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    "Customer is pushing back here: We're debugging a Email issue for a Growth workspace in Asia Pacific. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Can Atlas recover data that was already hard-deleted if I only know the old conversation ID?',
    'Customer is pushing back here: The knowledge base is silent about a refund exception for this Starter case. Should the assistant infer an exception because it sounds fair?',
    "Our Web Chat webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    "I might be mixing two rules up. We're on Growth in Canada. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'I might be mixing two rules up. A Enterprise account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    'Production support question: A major Voice feature is unavailable for many users but we have a material workaround. Is that P1 or P2?',
    'We changed a knowledge source seconds ago for our Web Chat workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    'Need an answer I can send to an admin: We changed a knowledge source seconds ago for our Voice workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    'This is from a real ticket-style scenario: A Growth account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    "Finance and support are telling me different things. Our Business workspace uses several API keys and together we're over 1,200 requests per minute. Can each key claim its own full limit, or is the limit shared?",
    'Quick sanity check — A Business production service is broadly unavailable with no reasonable workaround, but only one ticket is open. Is it still P1?',
    'This is from a real ticket-style scenario: SCIM deactivated an agent in Asia Pacific. Should the audit events that person created disappear too?',
    'Production support question: A Growth team deleted a Zalo conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    'Need an answer I can send to an admin: The right knowledge article exists, but an active metadata filter excludes its product line. Can the answer stage silently pull that article back in?',
    'This is from a real ticket-style scenario: A Starter production service is broadly unavailable with no reasonable workaround, but only one ticket is open. Is it still P1?',
    'Production support question: A Growth team deleted a Email conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    'Finance and support are telling me different things. SCIM deactivated an agent in Asia Pacific. Should the audit events that person created disappear too?',
    'Finance and support are telling me different things. Can JIT create a new member on first SSO login just because the email domain matches, even if workspace policy disables JIT?',
    'Finance and support are telling me different things. A Data Processing Addendum conflicts with general documentation on how customer data is processed in Canada. Which one controls that privacy question?',
    'We regenerated MFA recovery codes for an admin in a Business workspace. Are unused codes from the old set still valid?',
    'Need an answer I can send to an admin: A Business team deleted a Email conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    "Quick sanity check — We're debugging a Email issue for a Business workspace in Asia Pacific. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'I might be mixing two rules up. A Starter customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    "Finance and support are telling me different things. We're debugging a Email issue for a Enterprise workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'This is from a real ticket-style scenario: A Enterprise customer says a citation in an AI answer should count as a contract amendment. Is that what the policy says?',
    "Customer is pushing back here: Our WhatsApp webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    'Need an answer I can send to an admin: SCIM deactivated an agent in Canada. Should the audit events that person created disappear too?',
    'I might be mixing two rules up. We revoked a third-party connector token used by a Email integration. Does revocation automatically erase data imported last month?',
    'Production support question: A Zalo assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'Need an answer I can send to an admin: A Growth customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    'Customer is pushing back here: We changed a knowledge source seconds ago for our WhatsApp workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    'Quick sanity check — The knowledge base is silent about a refund exception for this Growth case. Should the assistant infer an exception because it sounds fair?',
    "Finance and support are telling me different things. We're debugging a Web Chat issue for a Business workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Customer is pushing back here: A Business production service is broadly unavailable with no reasonable workaround, but only one ticket is open. Is it still P1?',
    'Need an answer I can send to an admin: A Business team deleted a WhatsApp conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    'Quick sanity check — A Starter workspace has a legal hold on one record, but the normal retention period already expired. Should Atlas hard-delete it anyway?',
    "Production support question: Our Business workspace uses several API keys and together we're over 1,200 requests per minute. Can each key claim its own full limit, or is the limit shared?",
    'Production support question: We revoked a third-party connector token used by a Web Chat integration. Does revocation automatically erase data imported last month?',
    'Finance and support are telling me different things. We upgraded from Growth to Business halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    "Production support question: We're on Starter in Canada. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Quick sanity check — A Business account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    "Customer is pushing back here: Our Email webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    'Need an answer I can send to an admin: We reused an Idempotency-Key within 24 hours but changed the payload. Should Atlas accept the new payload as a new request?',
    'Finance and support are telling me different things. The current help article and a signed Enterprise order form disagree about an API limit for this Growth account. Which source controls the negotiated limit?',
    'A Growth customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    'This is from a real ticket-style scenario: Webhook verification works with the exact request bytes but fails after our framework parses and re-serializes JSON. Is that consistent with Atlas signing?',
    'Production support question: We upgraded from Growth to Business halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    'Finance and support are telling me different things. A Enterprise customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    "Quick sanity check — We're debugging a Voice issue for a Growth workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Customer is pushing back here: A Enterprise customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    'Customer is pushing back here: A Starter team deleted a Web Chat conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    'The current help article and a signed Enterprise order form disagree about an API limit for this Growth account. Which source controls the negotiated limit?',
    'Quick sanity check — A Business team deleted a Web Chat conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    "Production support question: Our Email webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    'Need an answer I can send to an admin: We changed a knowledge source seconds ago for our Web Chat workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    'Need an answer I can send to an admin: SCIM deactivated an agent in Asia Pacific. Should the audit events that person created disappear too?',
    "Quick sanity check — We're on Enterprise in European Union. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    "This is from a real ticket-style scenario: We're debugging a WhatsApp issue for a Enterprise workspace in Asia Pacific. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Production support question: A Data Processing Addendum conflicts with general documentation on how customer data is processed in Canada. Which one controls that privacy question?',
    'Production support question: A Starter customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    'Production support question: A Starter customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    "Need an answer I can send to an admin: We're debugging a WhatsApp issue for a Business workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Quick sanity check — A Enterprise workspace has a legal hold on one record, but the normal retention period already expired. Should Atlas hard-delete it anyway?',
    'Customer asked me this and I cannot find it in docs: Can a citation override a signed contract if the answer sounds more recent?',
    'Customer is pushing back here: SCIM deactivated an agent in Canada. Should the audit events that person created disappear too?',
    "This is from a real ticket-style scenario: We're debugging a Web Chat issue for a Growth workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'This is from a real ticket-style scenario: A Starter team deleted a Voice conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    'This is from a real ticket-style scenario: A Web Chat assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'We revoked a third-party connector token used by a WhatsApp integration. Does revocation automatically erase data imported last month?',
    'Need an answer I can send to an admin: A Email assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'Quick sanity check — A Security Addendum conflicts with a generic help-center article about a security commitment for a Growth customer. Which should support follow?',
    "Finance and support are telling me different things. We're on Growth in Canada. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'This is from a real ticket-style scenario: We upgraded from Enterprise to Starter halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    'Quick sanity check — The current help article and a signed Enterprise order form disagree about an API limit for this Starter account. Which source controls the negotiated limit?',
    'Production support question: A Enterprise production service is broadly unavailable with no reasonable workaround, but only one ticket is open. Is it still P1?',
    'Production support question: A Starter account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    'I might be mixing two rules up. The knowledge base is silent about a refund exception for this Growth case. Should the assistant infer an exception because it sounds fair?',
    "Finance and support are telling me different things. We're on Starter in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Need an answer I can send to an admin: We changed a knowledge source seconds ago for our Email workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    "I might be mixing two rules up. We're debugging a WhatsApp issue for a Business workspace in Asia Pacific. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'We think an API secret for a Business workspace leaked. What immediate action does the documentation call for?',
    'A Business customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    'Need an answer I can send to an admin: If our workspace content region is Canada, does that also force every billing record and anti-fraud signal to stay there?',
    'This is from a real ticket-style scenario: A Enterprise team deleted a WhatsApp conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    "Need an answer I can send to an admin: We're on Starter in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Production support question: A Data Processing Addendum conflicts with general documentation on how customer data is processed in European Union. Which one controls that privacy question?',
    'I might be mixing two rules up. The knowledge base is silent about a refund exception for this Business case. Should the assistant infer an exception because it sounds fair?',
    'If our workspace content region is Asia Pacific, does that also force every billing record and anti-fraud signal to stay there?',
    'A Email assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    "Quick sanity check — We're on Starter in United States. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Customer asked me this and I cannot find it in docs: Can Atlas recover data that was already hard-deleted if I only know the old conversation ID?',
    "I might be mixing two rules up. Our Web Chat webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    'Customer is pushing back here: A Starter customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    'I might be mixing two rules up. The current help article and a signed Enterprise order form disagree about an API limit for this Enterprise account. Which source controls the negotiated limit?',
    'Customer is pushing back here: A Growth customer says a citation in an AI answer should count as a contract amendment. Is that what the policy says?',
    'A Starter customer says a citation in an AI answer should count as a contract amendment. Is that what the policy says?',
    'A Starter account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    "We're on Enterprise in European Union. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    "Customer is pushing back here: We're on Business in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Production support question: We regenerated MFA recovery codes for an admin in a Business workspace. Are unused codes from the old set still valid?',
    'A Security Addendum conflicts with a generic help-center article about a security commitment for a Starter customer. Which should support follow?',
    "Quick sanity check — We're on Growth in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    "This is from a real ticket-style scenario: We're debugging a Voice issue for a Growth workspace in United States. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    "Our Zalo webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    "Quick sanity check — Our Growth workspace uses several API keys and together we're over 600 requests per minute. Can each key claim its own full limit, or is the limit shared?",
    "Production support question: We're on Enterprise in United States. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Customer is pushing back here: A Business customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    'Customer is pushing back here: If our workspace content region is Canada, does that also force every billing record and anti-fraud signal to stay there?',
    'Finance and support are telling me different things. A Starter customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    'This is from a real ticket-style scenario: A Security Addendum conflicts with a generic help-center article about a security commitment for a Starter customer. Which should support follow?',
    "Finance and support are telling me different things. We're on Starter in Canada. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Production support question: A Starter team deleted a Zalo conversation 5 days ago, no legal hold. Is it still in the normal recovery window?',
    "This is from a real ticket-style scenario: We're on Business in Canada. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'I might be mixing two rules up. A Growth workspace has a legal hold on one record, but the normal retention period already expired. Should Atlas hard-delete it anyway?',
    'Production support question: A Enterprise customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    'Quick sanity check — We changed a knowledge source seconds ago for our Zalo workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    'Production support question: The current help article and a signed Enterprise order form disagree about an API limit for this Starter account. Which source controls the negotiated limit?',
    'Customer is pushing back here: We changed a knowledge source seconds ago for our Email workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    "Finance and support are telling me different things. Our Web Chat webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    'Quick sanity check — We reused an Idempotency-Key within 24 hours but changed the payload. Should Atlas accept the new payload as a new request?',
    "Customer is pushing back here: We're debugging a Voice issue for a Starter workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'I might be mixing two rules up. A Data Processing Addendum conflicts with general documentation on how customer data is processed in European Union. Which one controls that privacy question?',
    "Finance and support are telling me different things. We're debugging a Voice issue for a Business workspace in United States. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'I might be mixing two rules up. We upgraded from Enterprise to Starter halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    "Customer is pushing back here: We're on Enterprise in United States. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    "Need an answer I can send to an admin: Our Email webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    'Finance and support are telling me different things. A Starter customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    'Finance and support are telling me different things. Webhook verification works with the exact request bytes but fails after our framework parses and re-serializes JSON. Is that consistent with Atlas signing?',
    'Production support question: A Business customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    "Quick sanity check — We're on Enterprise in United States. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Quick sanity check — A Security Addendum conflicts with a generic help-center article about a security commitment for a Business customer. Which should support follow?',
    'This is from a real ticket-style scenario: We changed a knowledge source seconds ago for our WhatsApp workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    'Finance and support are telling me different things. A Growth workspace has a legal hold on one record, but the normal retention period already expired. Should Atlas hard-delete it anyway?',
    "Finance and support are telling me different things. Our WhatsApp webhook failed delivery. What's the retry sequence before it reaches dead-letter state?",
    'Production support question: Can JIT create a new member on first SSO login just because the email domain matches, even if workspace policy disables JIT?',
    'Quick sanity check — A major Web Chat feature is unavailable for many users but we have a material workaround. Is that P1 or P2?',
    "I might be mixing two rules up. We're debugging a Web Chat issue for a Growth workspace in United States. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'I might be mixing two rules up. We changed a knowledge source seconds ago for our WhatsApp workflow and search still shows the previous text. Does Atlas promise zero indexing delay?',
    "Production support question: We're on Business in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'This is from a real ticket-style scenario: A Growth customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    'Production support question: A major Email feature is unavailable for many users but we have a material workaround. Is that P1 or P2?',
    'Need an answer I can send to an admin: A Business customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    "Quick sanity check — We're on Business in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Need an answer I can send to an admin: A Security Addendum conflicts with a generic help-center article about a security commitment for a Business customer. Which should support follow?',
    'This is from a real ticket-style scenario: A Growth customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    'Quick sanity check — If our workspace content region is Asia Pacific, does that also force every billing record and anti-fraud signal to stay there?',
    'This is from a real ticket-style scenario: A WhatsApp assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'Finance and support are telling me different things. A Business customer has a signed order form that overrides one commercial limit, but it says nothing about retention. Does that override silently replace the normal retention rule too?',
    "Quick sanity check — We're on Enterprise in Canada. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'I might be mixing two rules up. A Starter production service is broadly unavailable with no reasonable workaround, but only one ticket is open. Is it still P1?',
    "Customer is pushing back here: We're on Enterprise in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'A Starter customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    'Customer is pushing back here: A major Zalo feature is unavailable for many users but we have a material workaround. Is that P1 or P2?',
    'Our workspace is in Canada. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'Finance and support are telling me different things. A Growth team deleted a Voice conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    'Customer is pushing back here: If our workspace content region is European Union, does that also force every billing record and anti-fraud signal to stay there?',
    'This is from a real ticket-style scenario: Can JIT create a new member on first SSO login just because the email domain matches, even if workspace policy disables JIT?',
    'Production support question: We replayed a webhook; delivery ID changed but event ID stayed the same. Should our dedupe key be the event ID or the delivery ID?',
    'This is from a real ticket-style scenario: A Growth team deleted a Email conversation 2 days ago, no legal hold. Is it still in the normal recovery window?',
    'A Starter team deleted a WhatsApp conversation 2 days ago, no legal hold. Is it still in the normal recovery window?',
    "We're debugging a Email issue for a Starter workspace in United States. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Customer is pushing back here: We think an API secret for a Enterprise workspace leaked. What immediate action does the documentation call for?',
    "Quick sanity check — We're on Growth in European Union. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'This is from a real ticket-style scenario: The current help article and a signed Enterprise order form disagree about an API limit for this Business account. Which source controls the negotiated limit?',
    'A major Email feature is unavailable for many users but we have a material workaround. Is that P1 or P2?',
    'Production support question: A Business team deleted a Voice conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    "Finance and support are telling me different things. Our Growth workspace uses several API keys and together we're over 600 requests per minute. Can each key claim its own full limit, or is the limit shared?",
    "Customer is pushing back here: We're debugging a WhatsApp issue for a Growth workspace in Canada. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Customer is pushing back here: The knowledge base is silent about a refund exception for this Growth case. Should the assistant infer an exception because it sounds fair?',
    'A Enterprise team deleted a Web Chat conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    "Customer is pushing back here: We're debugging a Email issue for a Enterprise workspace in United States. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Quick sanity check — Our workspace is in Canada. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'Finance and support are telling me different things. SCIM deactivated an agent in European Union. Should the audit events that person created disappear too?',
    'Need an answer I can send to an admin: A Business workspace has a legal hold on one record, but the normal retention period already expired. Should Atlas hard-delete it anyway?',
    'Production support question: SCIM deactivated an agent in European Union. Should the audit events that person created disappear too?',
    "Finance and support are telling me different things. We're debugging a Zalo issue for a Growth workspace in Canada. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'Quick sanity check — We sent the same supported create request twice on Enterprise with the same Idempotency-Key within an hour. Should that create two resources?',
    'This is from a real ticket-style scenario: We think an API secret for a Enterprise workspace leaked. What immediate action does the documentation call for?',
    'Production support question: We revoked a third-party connector token used by a Email integration. Does revocation automatically erase data imported last month?',
    'This is from a real ticket-style scenario: A Growth team deleted a WhatsApp conversation 2 days ago, no legal hold. Is it still in the normal recovery window?',
    'Quick sanity check — The knowledge base is silent about a refund exception for this Enterprise case. Should the assistant infer an exception because it sounds fair?',
    'Finance and support are telling me different things. We think an API secret for a Starter workspace leaked. What immediate action does the documentation call for?',
    'Production support question: A Business customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    'Customer is pushing back here: A Starter workspace has a legal hold on one record, but the normal retention period already expired. Should Atlas hard-delete it anyway?',
    'Need an answer I can send to an admin: We revoked a third-party connector token used by a Voice integration. Does revocation automatically erase data imported last month?',
    'Finance and support are telling me different things. A Starter team deleted a Zalo conversation 8 days ago, no legal hold. Is it still in the normal recovery window?',
    'This is from a real ticket-style scenario: A Business workspace has a legal hold on one record, but the normal retention period already expired. Should Atlas hard-delete it anyway?',
    'I might be mixing two rules up. A Business customer says a citation in an AI answer should count as a contract amendment. Is that what the policy says?',
    'Customer is pushing back here: A major Voice feature is unavailable for many users but we have a material workaround. Is that P1 or P2?',
    'Customer is pushing back here: Our workspace is in Asia Pacific. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    "I might be mixing two rules up. We're on Business in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'I might be mixing two rules up. We upgraded from Growth to Business halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    "We're on Growth in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Customer is pushing back here: A Growth customer opened six tickets for a one-user configuration problem. Does the number of tickets by itself make it P1?',
    'Customer is pushing back here: A Growth team deleted a Web Chat conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    'Need an answer I can send to an admin: A Growth team deleted a Web Chat conversation 5 days ago, no legal hold. Is it still in the normal recovery window?',
    'I might be mixing two rules up. SCIM deactivated an agent in Asia Pacific. Should the audit events that person created disappear too?',
    'Production support question: A Business account is suspended for nonpayment. Does suspension itself instantly erase its customer content?',
    "Customer is pushing back here: Our Growth workspace uses several API keys and together we're over 600 requests per minute. Can each key claim its own full limit, or is the limit shared?",
    'Need an answer I can send to an admin: We upgraded from Business to Enterprise halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    'Customer is pushing back here: Can JIT create a new member on first SSO login just because the email domain matches, even if workspace policy disables JIT?',
    "Finance and support are telling me different things. We're debugging a Voice issue for a Growth workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    "This is from a real ticket-style scenario: We're on Growth in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'I might be mixing two rules up. A Starter team deleted a Web Chat conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    'I might be mixing two rules up. A Enterprise customer says a citation in an AI answer should count as a contract amendment. Is that what the policy says?',
    "Production support question: We're debugging a Zalo issue for a Growth workspace in United States. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    "Need an answer I can send to an admin: We're debugging a Zalo issue for a Starter workspace in Asia Pacific. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'This is from a real ticket-style scenario: We upgraded from Growth to Business halfway through the billing period and immediately scheduled a downgrade. Which part happens now and which waits for renewal?',
    "I might be mixing two rules up. We're debugging a Web Chat issue for a Starter workspace in European Union. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    "Production support question: We're debugging a Email issue for a Starter workspace in United States. Can support paste the whole customer conversation into an ordinary ticket just because it is easier?",
    'This is from a real ticket-style scenario: We sent the same supported create request twice on Growth with the same Idempotency-Key within an hour. Should that create two resources?',
    'I might be mixing two rules up. SCIM deactivated an agent in European Union. Should the audit events that person created disappear too?',
    'I might be mixing two rules up. The current help article and a signed Enterprise order form disagree about an API limit for this Starter account. Which source controls the negotiated limit?',
    'Customer is pushing back here: If our workspace content region is Asia Pacific, does that also force every billing record and anti-fraud signal to stay there?',
    'Quick sanity check — We revoked a third-party connector token used by a Email integration. Does revocation automatically erase data imported last month?',
    'I might be mixing two rules up. We revoked a third-party connector token used by a WhatsApp integration. Does revocation automatically erase data imported last month?',
    "Our Starter workspace uses several API keys and together we're over 300 requests per minute. Can each key claim its own full limit, or is the limit shared?",
    'This is from a real ticket-style scenario: The current help article and a signed Enterprise order form disagree about an API limit for this Enterprise account. Which source controls the negotiated limit?',
    "Need an answer I can send to an admin: We're on Growth in United States. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'Need an answer I can send to an admin: A Starter team deleted a Zalo conversation 2 days ago, no legal hold. Is it still in the normal recovery window?',
    'Quick sanity check — A Enterprise team deleted a Zalo conversation 2 days ago, no legal hold. Is it still in the normal recovery window?',
    'Customer is pushing back here: A Web Chat assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    "Need an answer I can send to an admin: We're on Business in Asia Pacific. What's the normal conversation retention window, and does it count from creation or from the latest activity?",
    'A major Zalo feature is unavailable for many users but we have a material workaround. Is that P1 or P2?',
    'Production support question: A Business team deleted a Web Chat conversation 12 days ago, no legal hold. Is it still in the normal recovery window?',
    'Quick sanity check — A major Zalo feature is unavailable for many users but we have a material workaround. Is that P1 or P2?',
    'Our workspace is in European Union. Do message content, indexed knowledge text, and conversation vectors all follow that content region?',
    'A WhatsApp assistant is below the configured confidence threshold and a human handoff starts. Should automated replies keep sending until an agent answers?',
    'Webhook verification works with the exact request bytes but fails after our framework parses and re-serializes JSON. Is that consistent with Atlas signing?',
    'Quick sanity check — Can JIT create a new member on first SSO login just because the email domain matches, even if workspace policy disables JIT?',
    'Quick sanity check — If our workspace content region is United States, does that also force every billing record and anti-fraud signal to stay there?',
]
